apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Longhorn node configuration
  - node-longhorn-shion-ubuntu-2505.yaml
  # Backup target configuration
  - backup-target.yaml
  # StorageClass definition
  - storageclass.yaml
  # Internal ingress for Longhorn UI
  - ingress.yaml
