apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: renovate-webhook
  namespace: renovate
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx-ssl
  tls:
    - hosts:
        - renovate.k.shion1305.com
      secretName: renovate-webhook-tls
  rules:
    - host: renovate.k.shion1305.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: renovate-github-eventsource-svc
                port:
                  number: 12000
