apiVersion: apps/v1
kind: Deployment
metadata:
  name: memgator
  namespace: memgator
  labels:
    app: memgator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memgator
  template:
    metadata:
      labels:
        app: memgator
    spec:
      containers:
      - name: memgator
        image: shion1305/memgator:1.0-rc9
        ports:
        - containerPort: 1208
          name: http
          protocol: TCP
        args:
          - "-H"
          - "0.0.0.0"
          - "-p"
          - "1208"
          - "-V"
          - "server"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 1208
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 1208
          initialDelaySeconds: 5
          periodSeconds: 5
