apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: memgator
  namespace: memgator
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx-internal
  tls:
    - hosts:
        - memgator.k.shion1305.com
  rules:
    - host: memgator.k.shion1305.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: memgator
                port:
                  number: 1208
