apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openwebui
  namespace: openwebui
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx-ssl
  tls:
    - hosts:
        - chat.k.shion1305.com
  rules:
    - host: chat.k.shion1305.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openwebui-open-webui
                port:
                  number: 80
