apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - vault-secret-store.yaml
  - external-secret.yaml
  - mcpo-deployment.yaml
  - network-policy-to-mcp.yaml
  - ingress.yaml
