apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - keycloak.yaml

# Note: Keycloak Operator and CRDs are installed manually via kubectl
# See installation commands in READDME.md
