apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres-cluster.yaml
  - tcp-service.yaml
  - ws-stream-deployment.yaml
  - mcp-connector.yaml
  - network-policy-mcp-to-postgres.yaml
  - grafana-config.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
  - grafana-ingress.yaml
  - prometheus.yaml
  - vault-secret-store.yaml
  - external-secret.yaml
