apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: librechat
  namespace: librechat
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx-internal
  tls:
    - hosts:
        - librechat.k.shion1305.com
  rules:
    - host: librechat.k.shion1305.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: librechat-librechat
                port:
                  number: 3080
